# Generated by Django 3.1.7 on 2022-04-04 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address1', models.CharField(blank=True, max_length=50, null=True)),
                ('address2', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verified_hash', models.CharField(blank=True, max_length=50, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('6c58db07-495d-434f-81bf-9048a84df741'), editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MusicianPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('cagegory', models.IntegerField(blank=True, null=True)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musician', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicianPostForOrder', to='api.musicianpost')),
            ],
        ),
        migrations.CreateModel(
            name='SystemFeeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('88275d0a-489f-4aba-8273-b89e680c1312'), editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orderSystemFee', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('availble_type', models.IntegerField(blank=True, null=True)),
                ('deadline', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(auto_now_add=True)),
                ('datetime', models.DateTimeField()),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicianpost', to='api.musicianpost')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3834f8b6-9199-4746-9817-cc7aeb5aca3e'), editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('widrawalDate', models.DateField()),
                ('expireDate', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orderPayment', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('readStatus', models.BooleanField(default=False)),
                ('all', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c398bb09-25a0-4206-b149-f6a32ad19570'), editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChattingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contents', models.CharField(blank=True, max_length=1000, null=True)),
                ('attach', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chattingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatting', to='api.chatting')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senderuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatting',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.order'),
        ),
        migrations.AddField(
            model_name='chatting',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatting',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1834640b-23f9-461d-be44-4c635eafd4a8'), editable=False, primary_key=True, serialize=False)),
                ('bankName', models.CharField(max_length=50)),
                ('AccountName', models.CharField(max_length=50)),
                ('branchName', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
